Installation:
  V1:
    Registry:
      Domain: quay.io
    Provider:
      AWS:
        AvailabilityZones:
          - eu-central-1a
          - eu-central-1b
          - eu-central-1c
    Docker:
      CIDR: "172.18.224.1/19"
    IPAM:
      NetworkCIDR: "10.35.0.0/17"
    Kubernetes:
      API:
        ClusterIPRange: "172.18.192.0/20"
